<a href="https://colab.research.google.com/github/iamwendellbalagot/google-colab/blob/master/Pytorch_Blitz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from __future__ import print_function
import torch

In [ ]:
x = torch.empty(5,3)
x

tensor([[3.4468e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.2582e-36]])

In [ ]:
x = torch.rand(5,3)
x

tensor([[0.9071, 0.0619, 0.4673],
        [0.1225, 0.6104, 0.0062],
        [0.5111, 0.0182, 0.5156],
        [0.6719, 0.0853, 0.5917],
        [0.7358, 0.4813, 0.9075]])

In [ ]:
x = torch.zeros((5,3), dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [ ]:
x = torch.tensor([5.4, 3.3])
x

tensor([5.4000, 3.3000])

In [ ]:
x = x.new_ones((5,3), dtype=torch.long)
print(x)

x = torch.rand_like(x, dtype=torch.float64)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[0.2165, 0.6143, 0.7782],
        [0.7633, 0.7143, 0.8908],
        [0.9637, 0.7012, 0.3255],
        [0.7498, 0.1734, 0.7024],
        [0.7678, 0.3396, 0.1638]], dtype=torch.float64)


In [ ]:
x.size()

torch.Size([5, 3])

In [ ]:
y = torch.rand((5,3))
print(x+y)

tensor([[0.2772, 1.5190, 1.3889],
        [0.8568, 0.8276, 1.2675],
        [1.8876, 1.5511, 0.6815],
        [1.1587, 1.0891, 1.3386],
        [0.8799, 1.2190, 0.1679]], dtype=torch.float64)


In [ ]:
result = torch.empty(5,3)
torch.add(x,y, out=result)
print(result)

tensor([[0.2772, 1.5190, 1.3889],
        [0.8568, 0.8276, 1.2675],
        [1.8876, 1.5511, 0.6815],
        [1.1587, 1.0891, 1.3386],
        [0.8799, 1.2190, 0.1679]])


In [ ]:
y

tensor([[0.0607, 0.9047, 0.6107],
        [0.0935, 0.1134, 0.3767],
        [0.9239, 0.8498, 0.3560],
        [0.4090, 0.9157, 0.6361],
        [0.1121, 0.8794, 0.0041]])

In [ ]:
x.t_()

tensor([[0.2165, 0.7633, 0.9637, 0.7498, 0.7678],
        [0.6143, 0.7143, 0.7012, 0.1734, 0.3396],
        [0.7782, 0.8908, 0.3255, 0.7024, 0.1638]], dtype=torch.float64)

In [ ]:
x = torch.rand(4,4)
print(x)

tensor([[0.1253, 0.3385, 0.2469, 0.9567],
        [0.9484, 0.0844, 0.2179, 0.6856],
        [0.6802, 0.7042, 0.5931, 0.2215],
        [0.8650, 0.2832, 0.6047, 0.5128]])


In [ ]:
x.view(-1,1,1)

tensor([[[0.1253]],

        [[0.3385]],

        [[0.2469]],

        [[0.9567]],

        [[0.9484]],

        [[0.0844]],

        [[0.2179]],

        [[0.6856]],

        [[0.6802]],

        [[0.7042]],

        [[0.5931]],

        [[0.2215]],

        [[0.8650]],

        [[0.2832]],

        [[0.6047]],

        [[0.5128]]])

In [ ]:
if torch.cuda.is_available():
  device  = torch.device('cuda')
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y 
  print(z)
  print(z.to())

True